site_name: Cuboid Manual
theme: 
  name: readthedocs
  logo: img/cuboid_dark.png
markdown_extensions:
  - admonition
  - footnotes
extra_css: [extra.css]
nav:
  - Home: '../'
  - About:
    - About Cuboid: "about/index.md"
    - License: "about/license.md"
    - Acknowledgements: "about/acknowledgements.md"
    - Support: "about/support.md"
  - Getting Started:
    - Getting Started: "getting-started/index.md"
    - Installing: "getting-started/installing.md"
  - Sections:
    - Importing Assets: "sections/importing.md"
    - User Interface: "sections/user-interface.md"